export const NOT_FOUND = 'NOT_FOUND';
export const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const VALIDATION_ERROR = 'VALIDATION_ERROR';
